version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - ollama

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: devops
      POSTGRES_PASSWORD: devops
      POSTGRES_DB: devops
    ports:
      - "5432:5432"

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"

  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3,lambda
    ports:
      - "4566:4566"