pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building...'
            }
        }

        stage('Test') {
            steps {
                echo 'Testing...'
            }
        }

        stage('Analyze Failure') {
            steps {
                script {
                    def logs = "Sample error: DB connection failed"

                    sh """
                    curl -X POST http://backend:5000/analyze \
                    -H "Content-Type: application/json" \
                    -d '{"logs": "${logs}"}'
                    """
                }
            }
        }
    }
}